import { PathDataType } from '../../types/types';

const pathData: PathDataType = {
  ultrasound: 'УЗД',
  fgds: 'ФГДС + h.pylori',
  sct: 'СКТ',
  petct: 'ПЕТ КТ',
  ecg: 'ЕКГ',
  pathistology: 'Патогістологічне дослідження ',
  usthyroid: 'УЗД щитовидної залози',
  usbreast: 'УЗД молочних залоз',
  echo: 'УЗД серця',
  usabdomen: 'УЗД ОЧП',
  general: 'Загальний Аналіз Крові',
  biochemistry: 'Біохімічний Аналіз Крові',
  urina: 'Загальний Аналіз Сечі',
  infections: 'На Інфекційні Захворювання',
  uskidney: 'УЗД нирок та сечовивідних шляхів',
  oro_bac_flora: 'Бакпосів із зіву',
  uro_bac_flora: 'Бакпосів сечі на мікрофлору',
  aslo: 'Антистрептолізин-О (АСЛ-О)',
  igG: 'Концентрація IgG в сироватці крові',
  hepatitis: 'Гепатити',
  hiv: 'Вірус імунодефіциту людини',
  herpes: 'Герпес віруси',
  familydoctor: 'Огляд сімейного лікаря',
  otolaryngologist: 'Огляд ЛОРа',
  urologist: 'Огляд уролога',
  hematologist: 'Огляд гематолога',
  mamologist: 'Огляд мамолога',
  diagnosis: 'Діагностика',
  consultations: 'Лікарі',
  analysis: 'Аналізи',
  treatment: 'Лікування',
  otosurgery: 'Оперативне втручання',
  chemotherapy: 'Хіміотерапія',
  radiationtherapy: 'Променева терапія',
};

export default pathData;
